import { Startup, RoadmapStage, PitchEvent, DigitalFootprintLog, StartupMetrics } from '@/types';

// ─── Mock Roadmap Stages ────────────────────────────────────────────────────
export const ROADMAP_STAGES: RoadmapStage[] = [
  {
    id: 'stage_1_discovery',
    order: 1,
    title: 'Problem Discovery',
    description: 'Identify and validate the core problem you are solving',
    phase: 'discovery',
    isGatekeeper: false,
    requiredArtifacts: [
      { key: 'problem_statement', label: 'Problem Statement Doc', type: 'file', isRequired: true },
      { key: 'customer_interviews', label: 'Customer Interviews (5+)', type: 'form', isRequired: true },
    ],
    unlockConditions: { previousStageCompleted: false, minScore: null, adminVerificationRequired: false },
  },
  {
    id: 'stage_2_validation',
    order: 2,
    title: 'Solution Validation',
    description: 'Validate your solution hypothesis with real users',
    phase: 'validation',
    isGatekeeper: false,
    requiredArtifacts: [
      { key: 'customer_dev_report', label: 'Customer Dev Report', type: 'file', isRequired: true },
      { key: 'value_proposition', label: 'Value Proposition Canvas', type: 'file', isRequired: true },
    ],
    unlockConditions: { previousStageCompleted: true, minScore: null, adminVerificationRequired: false },
  },
  {
    id: 'stage_3_mvp',
    order: 3,
    title: 'MVP Development',
    description: 'Build and launch your Minimum Viable Product',
    phase: 'building',
    isGatekeeper: true,
    requiredArtifacts: [
      { key: 'mvp_demo', label: 'MVP Demo / Link', type: 'file', isRequired: true },
      { key: 'unit_economics', label: 'Unit Economics Model', type: 'file', isRequired: true },
    ],
    unlockConditions: { previousStageCompleted: true, minScore: 40, adminVerificationRequired: true },
  },
  {
    id: 'stage_4_traction',
    order: 4,
    title: 'Traction & Growth',
    description: 'Achieve measurable traction and prove growth potential',
    phase: 'scaling',
    isGatekeeper: true,
    requiredArtifacts: [
      { key: 'traction_metrics', label: 'Traction Dashboard', type: 'metric', isRequired: true },
      { key: 'gtm_strategy', label: 'Go-To-Market Strategy', type: 'file', isRequired: true },
    ],
    unlockConditions: { previousStageCompleted: true, minScore: 60, adminVerificationRequired: true },
  },
  {
    id: 'stage_5_fundraising',
    order: 5,
    title: 'Investment Ready',
    description: 'Prepare for investor meetings and fundraising round',
    phase: 'fundraising',
    isGatekeeper: true,
    requiredArtifacts: [
      { key: 'pitch_deck', label: 'Pitch Deck (AI Scored)', type: 'file', isRequired: true },
      { key: 'financial_model', label: 'Financial Model (3yr)', type: 'file', isRequired: true },
      { key: 'executive_summary', label: 'Executive Summary', type: 'file', isRequired: true },
    ],
    unlockConditions: { previousStageCompleted: true, minScore: 75, adminVerificationRequired: true },
  },
];

// ─── Mock Startups ───────────────────────────────────────────────────────────
const baseMetrics: StartupMetrics = {
  mrr: 0, arr: 0, mau: 0, churnRate: 0,
  ltv: 0, cac: 0, ltvCacRatio: 0, runwayMonths: 0,
  teamSize: 2, updatedAt: new Date(),
};

export const MOCK_STARTUPS: Startup[] = [
  {
    id: 'startup_1',
    founderIds: ['founder_1'],
    founderName: 'Alibek Dzhaksybekov',
    name: 'PayFlow UZ',
    tagline: 'B2B Payment Infrastructure for Central Asia',
    industry: 'FinTech',
    stage: 'investment_ready',
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    status: 'investment_ready' as any,
    currentRoadmapStageId: 'stage_5_fundraising',
    roadmapProgress: 88,
    investmentReadyAt: new Date('2026-04-01'),
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date(),
    metrics: { ...baseMetrics, mrr: 28000, arr: 336000, mau: 1200, churnRate: 2.1, ltv: 4800, cac: 320, ltvCacRatio: 15, runwayMonths: 18, teamSize: 12, updatedAt: new Date() },
    dataRoom: { pitchDeckUrl: '#', financialModelUrl: '#', executiveSummaryUrl: '#', customerDevReportUrl: '#', legalDocsUrls: [] },
    aiScores: { pitchDeckScore: 82, financialModelScore: 78, overallReadinessScore: 85, lastScoredAt: new Date() },
    executiveSummaryAI: 'PayFlow UZ is building critical payment rails for the underbanked B2B segment in Central Asia. Strong LTV/CAC of 15x, consistent MRR growth, and a defensible regulatory moat position them well for a Series A.',
    tags: ['fintech', 'b2b', 'payments', 'central-asia'],
    location: 'Tashkent, UZ',
    description: 'PayFlow UZ provides seamless cross-border B2B payment infrastructure for businesses operating in Central Asia.',
  },
  {
    id: 'startup_2',
    founderIds: ['founder_2'],
    founderName: 'Madina Yusupova',
    name: 'EduStack',
    tagline: 'AI-Powered Upskilling Platform for Tech Talent',
    industry: 'EdTech',
    stage: 'growth',
    status: 'active',
    currentRoadmapStageId: 'stage_4_traction',
    roadmapProgress: 62,
    investmentReadyAt: null,
    createdAt: new Date('2025-12-15'),
    updatedAt: new Date(),
    metrics: { ...baseMetrics, mrr: 8500, arr: 102000, mau: 3400, churnRate: 4.2, ltv: 1200, cac: 180, ltvCacRatio: 6.7, runwayMonths: 9, teamSize: 6, updatedAt: new Date() },
    dataRoom: { pitchDeckUrl: '#', financialModelUrl: null, executiveSummaryUrl: null, customerDevReportUrl: '#', legalDocsUrls: [] },
    aiScores: { pitchDeckScore: 71, financialModelScore: null, overallReadinessScore: 62, lastScoredAt: new Date() },
    executiveSummaryAI: 'EduStack demonstrates solid user growth with 3.4K MAU. The team needs to improve unit economics — LTV/CAC at 6.7x is decent but CAC could be reduced. Financial model and executive summary are outstanding items before investment readiness.',
    tags: ['edtech', 'ai', 'b2c', 'upskilling'],
    location: 'Almaty, KZ',
    description: 'EduStack uses AI to create personalized upskilling paths for tech talent across Central Asia.',
  },
  {
    id: 'startup_3',
    founderIds: ['founder_3'],
    founderName: 'Rustam Khasanov',
    name: 'AgriSense',
    tagline: 'IoT & AI for Smart Agriculture',
    industry: 'AgriTech',
    stage: 'mvp',
    status: 'active',
    currentRoadmapStageId: 'stage_3_mvp',
    roadmapProgress: 38,
    investmentReadyAt: null,
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date(),
    metrics: { ...baseMetrics, mrr: 1200, arr: 14400, mau: 280, churnRate: 8.1, ltv: 600, cac: 420, ltvCacRatio: 1.4, runwayMonths: 6, teamSize: 4, updatedAt: new Date() },
    dataRoom: { pitchDeckUrl: '#', financialModelUrl: null, executiveSummaryUrl: null, customerDevReportUrl: null, legalDocsUrls: [] },
    aiScores: { pitchDeckScore: 54, financialModelScore: null, overallReadinessScore: 38, lastScoredAt: new Date() },
    executiveSummaryAI: 'AgriSense is early-stage with promising technology but challenging unit economics. LTV/CAC at 1.4x is critically low. Recommend focusing on niche customer segment to improve retention and reduce CAC before next funding round.',
    tags: ['agritech', 'iot', 'ai', 'b2b'],
    location: 'Bishkek, KG',
    description: 'AgriSense provides IoT sensors and AI analytics to help farmers optimize yield and reduce water consumption.',
  },
  {
    id: 'startup_4',
    founderIds: ['founder_4'],
    founderName: 'Dilnoza Rakhimova',
    name: 'HealthLink',
    tagline: 'Telemedicine for Remote Communities',
    industry: 'HealthTech',
    stage: 'validation',
    status: 'active',
    currentRoadmapStageId: 'stage_2_validation',
    roadmapProgress: 21,
    investmentReadyAt: null,
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date(),
    metrics: { ...baseMetrics, mrr: 0, arr: 0, mau: 45, churnRate: 0, ltv: 0, cac: 0, ltvCacRatio: 0, runwayMonths: 4, teamSize: 3, updatedAt: new Date() },
    dataRoom: { pitchDeckUrl: null, financialModelUrl: null, executiveSummaryUrl: null, customerDevReportUrl: '#', legalDocsUrls: [] },
    aiScores: { pitchDeckScore: null, financialModelScore: null, overallReadinessScore: 21, lastScoredAt: null },
    executiveSummaryAI: null,
    tags: ['healthtech', 'telemedicine', 'b2c', 'rural'],
    location: 'Dushanbe, TJ',
    description: 'HealthLink connects remote communities with qualified doctors through a simple mobile telemedicine platform.',
  },
];

// ─── Mock Pitch Events ───────────────────────────────────────────────────────
export const MOCK_PITCHES: PitchEvent[] = [
  {
    id: 'pitch_1',
    startupId: 'startup_1',
    startupName: 'PayFlow UZ',
    founderIds: ['founder_1'],
    investorId: 'investor_1',
    investorName: 'Aibek Ventures',
    status: 'feedback_pending',
    request: { sentAt: new Date('2026-05-01'), proposedDate: new Date('2026-05-10'), message: 'We would love to present our traction metrics and Series A thesis.', snapshotScore: 85 },
    meeting: { confirmedDate: new Date('2026-05-10'), calendarEventId: 'cal_1', location: 'online', meetingUrl: 'https://meet.google.com/abc-def-ghi' },
    investorResponse: { respondedAt: new Date('2026-05-03'), rejectionReason: null },
    feedback: {
      requestedAt: new Date('2026-05-10'),
      submittedAt: null,
      overallImpression: 'yes',
      scores: { team: 4, market: 5, product: 4, traction: 4, financials: 4 },
      textFeedback: '',
      nextStep: 'follow_up',
    },
    createdAt: new Date('2026-05-01'),
    updatedAt: new Date(),
  },
  {
    id: 'pitch_2',
    startupId: 'startup_2',
    startupName: 'EduStack',
    founderIds: ['founder_2'],
    investorId: 'investor_1',
    investorName: 'Aibek Ventures',
    status: 'pending',
    request: { sentAt: new Date('2026-05-12'), proposedDate: new Date('2026-05-20'), message: 'EduStack has hit $8.5K MRR with strong user retention. Ready to discuss Series A.', snapshotScore: 62 },
    meeting: { confirmedDate: null, calendarEventId: null, location: 'online', meetingUrl: null },
    investorResponse: { respondedAt: null, rejectionReason: null },
    createdAt: new Date('2026-05-12'),
    updatedAt: new Date(),
  },
];

// ─── Mock Digital Footprint Logs ─────────────────────────────────────────────
export const MOCK_LOGS: DigitalFootprintLog[] = [
  { id: 'log_1', startupId: 'startup_1', actorId: 'founder_1', actorRole: 'founder', eventType: 'artifact_uploaded', description: 'Uploaded Pitch Deck v3.2 to Data Room', metadata: { artifactKey: 'pitch_deck' }, timestamp: new Date('2026-05-08'), timeToExecutionHours: null },
  { id: 'log_2', startupId: 'startup_1', actorId: 'ai_copilot', actorRole: 'ai_copilot', eventType: 'ai_analysis_done', description: 'AI scored Pitch Deck: 82/100. Strong market slide, weak competitive moat section.', metadata: { score: 82 }, timestamp: new Date('2026-05-08'), timeToExecutionHours: 0.5 },
  { id: 'log_3', startupId: 'startup_1', actorId: 'founder_1', actorRole: 'founder', eventType: 'metric_updated', description: 'Updated MRR: $24K → $28K. MAU: 1,100 → 1,200', metadata: { oldMRR: 24000, newMRR: 28000 }, timestamp: new Date('2026-05-05'), timeToExecutionHours: null },
  { id: 'log_4', startupId: 'startup_1', actorId: 'founder_1', actorRole: 'founder', eventType: 'pitch_requested', description: 'Sent pitch request to Aibek Ventures for $1.5M Series A', metadata: { investorId: 'investor_1', amount: 1500000 }, timestamp: new Date('2026-05-01'), timeToExecutionHours: null },
  { id: 'log_5', startupId: 'startup_1', actorId: 'admin_1', actorRole: 'admin', eventType: 'stage_completed', description: 'Stage "Investment Ready" verified and unlocked by UNTITLED team', metadata: { stageId: 'stage_5_fundraising' }, timestamp: new Date('2026-04-28'), timeToExecutionHours: 24 },
];
